# 自动部署的名称
name: GitHub pages deploy

# 自动部署的条件
on:
  push:
    branches:
      - main

jobs:
  # 构建网站并部署到 GitHub Pages
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/cache@v3
        id: node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npm run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist
          clean: true
          force: true
          token: ${{ secrets.ACCESS_TOKEN }}
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@releases/v4
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 也就是我们刚才生成的 secret
      #     BRANCH: gh-pages # 部署到 gh-pages 分支，因为 main 分支存放的一般是源码，而 gh-pages 分支则用来存放生成的静态文件
      #     FOLDER: src/.vuepress/dist # vuepress 生成的静态文件存放的地方
